---
languages:
   JavaScript: true
   Python: true
engines:
  eslint:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.py"
  - "**.scss"
  - "**.js"
  - "**.jsx"
exclude_paths: []
