sudo: false

language: python


cache:
    directories:
        - $HOME/.cache/pip

before_install:
  - pip install -r requirements.txt
  - npm config set python /usr/bin/python2.7
  - npm install
  - npm run build
node_js:
  - "4"
  - "0.12"
python:
  - "3.5"

addons:
  ssh_known_hosts: github.com
  code_climate:
    repo_token: 267de20fcb1419ff02cfe22e5009111ffc86347f398762cbb700ad56f8279ca6

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e72c826c6364f1f79f02
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
