sudo: false

language: python

node_js:
  - "4"
  - "0.12"
python:
  - "3.5"

env:
  global:
    - BEAVY_ENV=TEST
  matrix:
    - APP=minima
    - APP=hacker_news
    # --------------------- HERE -------------------
    # ADD YOUR APP HERE (and outcomments some others)
    # to make your travis run against your App tests,
    # like so:
    # - APP=my_app
    # --------------------- HERE -------------------

before_install:
  # NPM-gyp weirdly needs python2.7 (no Python3 support)
  # so set that before we are running the installs
  - npm config set python /usr/bin/python2.7
  - npm install

before_script:
  # setup test database
  - psql -c 'create database "beavy-test";' -U postgres
  # copy our test configuration to main
  - cp -f "beavy_apps/$APP/tests/config.yml" config.yml
  # building the javascript & js
  - npm run build
  # and migrate the database – this needs the manifest.json
  # and can only happen after the npm build!
  - python manager.py db upgrade heads


script:
  # we are starting with running all unit tests
  - py.test beavy beavy_modules beavy_apps

  # starting up test-server
  - flask --app=main run &
  # and running behaviour tests against it
  - python manager.py behave_tests


cache:
    directories:
        - $HOME/.cache/pip

services:
  - redis-server

addons:
  ssh_known_hosts: github.com
  postgresql: "9.4"
  code_climate:
    repo_token: 267de20fcb1419ff02cfe22e5009111ffc86347f398762cbb700ad56f8279ca6

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e72c826c6364f1f79f02
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
