sudo: false

language: python

python:
  - '3.5'

env:
  global:
    - BEAVY_ENV=TEST
    - secure: 42qbN2sBRUwB8q99XdMJDsr1FelB3fUA8wRjRbH7ZGKRDH6CKHALno/RV2QIzpbJTlwi/6ax5MV3FQTEPN5p726Zj1JiwOun3RW2kRdqCm/xNGyh4B5FxJxyzq0hSIFdJCXihJd1Frm2JltHMkRCadl6VtlmdY9L7N1SRHQoJs0X4wU354LJFpDu2trBZKESUWee73VgdynDwlT6nehwcj42TxyXt9lr3moZUHLIfXvnyMFL7tp1CDMdbAkD4m1hq1UG1jxHQRbHfzTEtem+8oVAi8I3Hrpds4/lnIjP6/LJi8bR3c9rKKykKe1EKZnhYUf/lwD00jdR4g8c1tR3F/kTByFjxGFRfpRUzJXi6dD8Q2JOdu8zVAuIgnZg2Gh+c5z+V3/L27ax1x4sYyiXbi/lQpbE6XSkn4wLWi9Y1TK1kl1N92NkVipLwHz535tcWLwQ9KwzpVUBznGcYw5XQO3sbVcSF4PiEpiET+MjwV5o5MkOfD67FATZo9GlSwKpmSoSsd2JgpjzieRNt+VDyC4liDWco2HA3191DSO2f/q91w3bpwlGRCKP/X78npeIVGCMOzWSnTmPtOLZd3MjC/g/HFb90SG6cjAC1nTkR8RHTAXYBSnUZgr1Gl/8A1I86LSDKhXGoBGHjJTFt0ViAX+Ho9Yn0LCrtrN7SeiuSEs=
  matrix:
    - APP=minima
    - APP=hacker_news

before_install:
  # use NVM to install latest stable NODE – the predelivered
  # one isn't able to build our es6 modules
  - nvm install stable
  # NPM-gyp weirdly needs python2.7 (no Python3 support)
  # so set that before we are running the installs
  - npm config set python /usr/bin/python2.7
  # install all node dependencies
  - npm install
  # install coveralls to send coverage stats there
  - pip install coveralls

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - psql -c 'create database "beavy-test";' -U postgres
  - cp -f "beavy_apps/$APP/tests/config.yml" config.yml
  - npm run build
  - python manager.py db upgrade heads


script:
  # we are starting with running all unit tests
  - py.test --cov-config .coveragerc --cov=beavy --cov=beavy_modules --cov=beavy_apps beavy beavy_modules beavy_apps
  - mv .coverage .coverage.pytest
  # lets run jstests
  - npm test
  # starting up test-server
  # and running behaviour tests against it
  - |
    #!/bin/bash
    set -e
    # -a means we are appending the coverage
    coverage run -a manager.py runserver -R &
    python manager.py behave
    # shutting down gracefully so coverage is written
    curl http://localhost:5000/__TESTS__/shutdown
    # give it a few seconds to stop the process
    sleep 3

after_success:
  - coverage report -m
  - coveralls
  - python scripts/travis_after_all.py && python scripts/auto_pr.py || echo "skipped"


cache:
  directories:
    - $HOME/.cache/pip

services:
  - redis-server

addons:
  ssh_known_hosts: github.com
  postgresql: '9.4'
  code_climate:
    repo_token: 267de20fcb1419ff02cfe22e5009111ffc86347f398762cbb700ad56f8279ca6

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e72c826c6364f1f79f02
    on_success: change
    on_failure: always
    on_start: never
