sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

before_install:
  - pip install -r requirements.txt
  - npm config set python /usr/bin/python2.7
  - npm install
  - npm run build
node_js:
  - "4"
  - "0.12"
python:
  - "3.5"

addons:
    code_climate:
        repo_token: 267de20fcb1419ff02cfe22e5009111ffc86347f398762cbb700ad56f8279ca6