COMMON: &common
  DEBUG: False
  TESTING: False
  SECURITY_CONFIRMABLE: True
  SECURITY_TRACKABLE: True
  SOCIAL_LOGINS: {}
  SECURITY_PASSWORD_HASH: "bcrypt"
  RATELIMIT_HEADERS_ENABLED: True
  RATELIMIT_GLOBAL: "200/hour"
  HOME_URL: '/hello'


DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SECRET_KEY: "asdfx123456"
  SQLALCHEMY_DATABASE_URI: "postgresql://localhost/beavy-dev"
  SQLALCHEMY_ECHO: True
  SECURITY_REGISTERABLE: True
  CELERY_BROKER_URL: redis://localhost:6379
  CELERY_RESULT_BACKEND: redis://localhost:6379
  SECURITY_PASSWORD_SALT: "__DEV"
  RATELIMIT_ENABLED: False

TEST: &test
  <<: *common
  TESTING: True
  CELERY_BROKER_URL: redis://localhost:6379
  CELERY_RESULT_BACKEND: redis://localhost:6379
  SQLALCHEMY_DATABASE_URI: "postgresql://localhost/beavy-test"
  SECURITY_PASSWORD_SALT: "__TEST"
  SECRET_KEY: "TEST_DONT_EVER_USE"
  RATELIMIT_ENABLED: False
  LOGIN_DISABLED: False

PRODUCTION: &production
  <<: *common
  CELERY_BROKER_URL: amqp://guest:guest@broker:5672//
  CELERY_RESULT_BACKEND: 'rpc://'
  CELERY_RESULT_PERSISTENT: False  
  SQLALCHEMY_DATABASE_URI: "postgresql://postgres@db/beavy"
