COMMON: &common
  DEBUG: False
  TESTING: False
  SECURITY_CONFIRMABLE: True
  SECURITY_TRACKABLE: True
  SOCIAL_LOGINS: {}
  SECURITY_PASSWORD_HASH: "bcrypt"
  RATELIMIT_HEADERS_ENABLED: True
  RATELIMIT_GLOBAL: "200/hour"
  HOME_URL: '/hello'


DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SECRET_KEY: "asdfx123456"
  SQLALCHEMY_DATABASE_URI: "postgresql://localhost/beavy-dev"
  SQLALCHEMY_ECHO: True
  SECURITY_REGISTERABLE: True
  CELERY_BROKER_URL: redis://localhost:6379
  CELERY_RESULT_BACKEND: redis://localhost:637
  SECURITY_PASSWORD_SALT: "__DEV"
  RATELIMIT_ENABLED: False

PRODUCTION: &production
  <<: *common

