COMMON: &common
  DEBUG: False
  TESTING: False
  SECURITY_CONFIRMABLE: True
  SECURITY_TRACKABLE: True
  SOCIAL_LOGINS: {}

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SECRET_KEY: "asdfx123456"
  SQLALCHEMY_DATABASE_URI: "postgresql://localhost/beavy-dev"
  SQLALCHEMY_ECHO: True

PRODUCTION: &production
  <<: *common

