COMMON: &common
  DEBUG: False
  TESTING: False
  SECRET_KEY: "asdfx123456"

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: "postgresql://localhost/beavy-dev"
  SQLALCHEMY_ECHO: True

PRODUCTION: &production
  <<: *common

